import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          className="navbar"
          style={{
            width: "100%",
            padding: "15px",
            borderBottom: "1px solid #ccc",
            display: "flex",
            alignItems: "flex-start",
            gap: "20px",
            marginBottom: "30px",
            color: "#777",
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/articles">Articles</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
